"""Generate a ``sys.set_lazy_imports_filter`` module from the analysis.

PEP 810 says of its filter hook that "static analysis tools could detect modules
with side effects and automatically configure filters".  This is that.

The keyword-based codemod converts imports one statement at a time, which is
precise but requires touching every file.  The filter is the other half: run the
whole application with ``-X lazy_imports=all`` and let a generated deny-list
force back to eager exactly those modules the analysis found unsafe.  No source
changes at all, at the cost of a coarser granularity -- the filter sees module
names, not import sites.

Two details of the hook shape the generated code.  It is consulted when the
import statement *executes*, not when the proxy is reified, so installing it
from inside the application's own entry point is too late for that entry point's
own imports; it belongs in ``sitecustomize`` or a wrapper.  And the filter runs
on every import in the process, so it is written to be cheap: set membership and
prefix checks, with a small cache.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field

__all__ = ["FilterPlan", "render_filter_module"]

_TEMPLATE = '''"""Lazy-import filter generated by pep810 on {timestamp}.

Install this before the application starts, not from inside it: PEP 810
consults the filter when an import statement runs, so a filter installed at the
top of your entry point cannot affect the imports above it.  Either name this
module ``sitecustomize.py`` somewhere on ``sys.path``, or import it from a
wrapper script that then imports the real entry point.

    # wrapper.py
    import {module_name}   # installs the filter
    import myapp.cli
    myapp.cli.main()

Then run with lazy imports on by default::

    python -X lazy_imports=all wrapper.py

Regenerate with ``pep810 filter`` after changing the code; the deny list is
derived from static analysis and goes stale as the code moves.
"""

from __future__ import annotations

import sys

#: Modules that must be imported eagerly.  Each has an import-time side effect
#: that other code depends on having already happened.  Listing a package here
#: also forces its submodules eager, since importing one runs the package's
#: ``__init__`` either way.
EAGER_MODULES: frozenset[str] = frozenset({{
{eager_entries}
}})

#: Any module under one of these prefixes is forced eager, package and all.
EAGER_PREFIXES: tuple[str, ...] = ({eager_prefixes})

#: When non-empty, only modules under these prefixes may be lazy; everything
#: else stays eager.  This is the conservative way to adopt ``lazy_imports=all``:
#: start with your own code and widen once it holds.
LAZY_ONLY_PREFIXES: tuple[str, ...] = ({lazy_prefixes})

_cache: dict[str, bool] = {{}}


def _decide(imported: str) -> bool:
    # Importing a submodule executes every parent package's __init__, so a
    # module on the deny list also disqualifies everything beneath it.
    parts = imported.split(".")
    for stop in range(len(parts), 0, -1):
        if ".".join(parts[:stop]) in EAGER_MODULES:
            return False
    for prefix in EAGER_PREFIXES:
        if imported == prefix or imported.startswith(prefix + "."):
            return False
    if LAZY_ONLY_PREFIXES:
        for prefix in LAZY_ONLY_PREFIXES:
            if imported == prefix or imported.startswith(prefix + "."):
                return True
        return False
    return True


def lazy_import_filter(importing, imported, fromlist) -> bool:
    """Return True to allow a lazy import, False to force it eager.

    The signature is PEP 810's: ``importing`` is the module running the import
    (or None), ``imported`` is the target's name, and ``fromlist`` holds the
    names of a ``from`` import (or None).
    """
    decision = _cache.get(imported)
    if decision is None:
        decision = _decide(imported)
        _cache[imported] = decision
    return decision


def install(mode: str = "{mode}") -> None:
    """Install the filter and, unless mode is "normal", switch lazy imports on."""
    sys.set_lazy_imports_filter(lazy_import_filter)
    if mode != "normal":
        sys.set_lazy_imports(mode)


if hasattr(sys, "set_lazy_imports_filter"):
    install()
'''


@dataclass
class FilterPlan:
    """What the generated filter should deny, allow and switch on."""

    #: Exact module names that must stay eager.
    eager_modules: set[str] = field(default_factory=set)
    #: Package prefixes that must stay eager.
    eager_prefixes: list[str] = field(default_factory=list)
    #: When set, only these prefixes may be lazy.
    lazy_only_prefixes: list[str] = field(default_factory=list)
    #: PEP 810 mode the generated module installs: "all" or "normal".
    mode: str = "all"
    #: Why each module is on the deny list, for the generated comments.
    reasons: dict[str, str] = field(default_factory=dict)

    def deny(self, module: str, reason: str) -> None:
        """Add ``module`` to the deny list, keeping the first reason given."""
        self.eager_modules.add(module)
        self.reasons.setdefault(module, reason)


def render_filter_module(plan: FilterPlan, module_name: str = "lazy_filter") -> str:
    """Render the plan as an installable Python module."""
    entries = []
    for module in sorted(plan.eager_modules):
        reason = plan.reasons.get(module)
        if reason:
            entries.append(f"    # {_one_line(reason)}")
        entries.append(f"    {module!r},")
    if not entries:
        entries.append("    # nothing needs forcing eager; the analysis found no blockers")

    return _TEMPLATE.format(
        timestamp=datetime.datetime.now().strftime("%Y-%m-%d"),
        module_name=module_name,
        eager_entries="\n".join(entries),
        eager_prefixes=_render_tuple(plan.eager_prefixes),
        lazy_prefixes=_render_tuple(plan.lazy_only_prefixes),
        mode=plan.mode,
    )


def _render_tuple(values: list[str]) -> str:
    """Render tuple members, collapsing the empty case to nothing."""
    if not values:
        return ""
    body = "".join(f"    {value!r},\n" for value in sorted(values))
    return f"\n{body}"


def _one_line(text: str, limit: int = 96) -> str:
    flat = " ".join(text.split())
    return flat if len(flat) <= limit else flat[: limit - 3] + "..."
